---
version: '3'
services:

  db:
      image: postgres:14.1-alpine
      restart: always
      container_name: fpl_postgres
      environment:
        - POSTGRES_USER=calumjackson
        - POSTGRES_PASSWORD=postgres
      ports:
        - '5432:5432'
      volumes: 
        - db:/var/lib/postgresql/data
        - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

        
volumes:
  db:
    driver: local